// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Fun_M","status":true,"description":"全局工具函数。","parameters":{}},
{"name":"Fun_Date","status":true,"description":"全局时间功能","parameters":{}},
{"name":"Fun_Core","status":true,"description":"核心","parameters":{}},
{"name":"Fun_Bag","status":true,"description":"背包","parameters":{}},
{"name":"Fun_Destination","status":true,"description":"地图点击图标","parameters":{}},
{"name":"Fun_Event_NameOrImage","status":true,"description":"修改事件名字和图像","parameters":{}},
{"name":"Fun_Event_Plant","status":true,"description":"农作物的编号记录","parameters":{}},
{"name":"Fun_Event_Var","status":true,"description":"事件变量","parameters":{}},
{"name":"Fun_MapName","status":true,"description":"地图名字右下角","parameters":{}},
{"name":"Fun_Event_Glow","status":true,"description":"一个可以发光的事件","parameters":{}},
{"name":"Fun_Map_CoolBar","status":true,"description":"采集进度条显示。","parameters":{}},
{"name":"Fun_MessWindow","status":true,"description":"消息窗口 全局可用 。","parameters":{}},
{"name":"Fun_MoveDire","status":true,"description":"移动时先转向","parameters":{}},
{"name":"Fun_TitleBgmWaiting","status":true,"description":"开始游戏标题界面 等待音乐播放完毕在弹出游戏窗口","parameters":{}},
{"name":"Fun_Seed_ID","status":true,"description":"种子编号","parameters":{}},
{"name":"Fun_MapShow_Seed_ID","status":true,"description":"地图上显示当前种子名称","parameters":{}},
{"name":"Fun_EventLocation","status":true,"description":"保存地图上的事件位置","parameters":{}}
];
